server.port: 8080
management:
  endpoints:
    web.base-path: /
    web.exposure.include: "*"
    enabled-by-default: true
  endpoint:
    health.enabled: true
    health.show-details: always

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.jdbc:.lob.non_contextual_creation: true

server.servlet.context-path: /api

security:
  oauth2:
    client:
      client-id: app
      client-secret: $2a$04$hqawBldLsWkFJ5CVsvtL7ed1z9yeoknfuszPOEHWzxfLBoViK6OVi
  jwt:
    key-store: "${JWT_KEY_STORE}"
    key-store-password: "${JWT_KEY_STORE_PASS}"
    key-pair-alias: "${JWT_KEYPAIR_ALIAS}"
    key-pair-password: "${JWT_KEYPAIR_PASS}"
