server.port: 8080
management:
  endpoints:
    web.base-path: /
    web.exposure.include: "*"
    enabled-by-default: true
  endpoint:
    health.enabled: true
    health.show-details: always


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.jdbc:.lob.non_contextual_creation: true

server.servlet.context-path: /api

tcp:
  key-store:
    name: server.jks
    password: 74Ew4g77XGnFC
    alias: server
  web-client-configuration:
    access-token-validity-in-seconds: 3600
    refresh-token-validity-in-seconds-for-remember-me: 604800
    client-id: web_app
    secret: $2a$04$hqawBldLsWkFJ5CVsvtL7ed1z9yeoknfuszPOEHWzxfLBoViK6OVi

logging:
  level:
    root: ALL