version: "3.0"
services:
  api:
    image: 090999229429.dkr.ecr.${AWS_REGION}.amazonaws.com/tcp-java-api
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      # ecs-cli compose substitutes these in, from .env in this directory:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_KEY_STORE: ${JWT_KEY_STORE}
      JWT_KEY_STORE_PASS: ${JWT_KEY_STORE_PASS}
      JWT_KEYPAIR_ALIAS: ${JWT_KEYPAIR_ALIAS}
      JWT_KEYPAIR_PASS: ${JWT_KEYPAIR_PASS}
    working_dir: /app
