version: "3.0"
services:
  api:
    image: 090999229429.dkr.ecr.us-east-1.amazonaws.com/tcp-java-api
    ports:
      - "8080:8080"
      - "5005:5005"
    links: [ "db:db" ]
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: api_user
      DB_PASSWORD: api_password
      # who substitutes these in? docker-compose? will ecs-cli compose do that?
      JWT_KEY_STORE: ${JWT_KEY_STORE}
      JWT_KEY_STORE_PASS: ${JWT_KEY_STORE_PASS}
      JWT_KEYPAIR_ALIAS: ${JWT_KEYPAIR_ALIAS}
      JWT_KEYPAIR_PASS: ${JWT_KEYPAIR_PASS}
    working_dir: /app
